services:
  whatsapp-bridge:
    build:
      context: ./whatsapp-bridge
      dockerfile: Dockerfile
    container_name: whatsapp-bridge
    ports:
      - "8080:8080"
    volumes:
      # Mount the store directory to persist WhatsApp authentication and messages
      - ./whatsapp-bridge/store:/app/store
    environment:
      - CGO_ENABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ls /app/store || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
